configuracao:
  monolito:
    url: http://localhost:8080
server:
  port: 8081
spring:

  application:
    name: "eats-pagamento"
    profiles:
    active: default
  cloud:
    config:
      uri: http://localhost:8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
